version: '3.9'
services:
  apigateway:
    image: registry.gitlab.com/maissacrement/docker/apigateway/apigateway
    #build:
    #  context: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 5000:5000